version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - git clone https://github.com/serandules/deploy.git
      - cd deploy
      - ./components ${NAME} ${REVISION}
      - echo Build completed on `date`
